name: bigid_bgcheck

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:  '*'

jobs:
  pipeline:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      PROJ_DIR: "/home/runner/work/bigid_bgcheck/bigid_bgcheck/"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'

    - name: Run Install
      run: |
        sudo apt-get -yqq install libpq-dev
        gem update --system
        gem install rake
        gem install bundler -v ">= 1.2"
        bundle install

    - name: Run Linter (rubocop)
      run: |
        bundle exec rubocop --format json -o report.json

    - name: Run Tests (rspec)
      run: |
        bundle exec rspec
        ruby -rjson -e 'sqube = JSON.load(File.read("coverage/.resultset.json"))["RSpec"]["coverage"].transform_values {|lines| lines["lines"]}; total = { "RSpec" => { "coverage" => sqube, "timestamp" => Time.now.to_i }}; puts JSON.dump(total).gsub(ENV["PROJ_DIR"],"/github/workspace/")' > coverage/.resultset.solarqube.json

    - uses: sonarsource/sonarqube-scan-action@master
      if: github.ref == 'refs/heads/master'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # If you wish to fail your job when the Quality Gate is red, uncomment the
        # following lines. This would typically be used to fail a deployment.
        # - uses: sonarsource/sonarqube-quality-gate-action@master
        #   timeout-minutes: 5
        #   env:
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
