name: bigid_bgcheck

on:
  push:
    branches: '*'
  pull_request:
    branches:  '*'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'

    - name: Run Install
      run: |
        sudo apt-get -yqq install libpq-dev
        gem update --system
        gem install rake
        gem install bundler -v ">= 1.2"
        bundle install

    - name: Run Linter (rubocop)
      run: |
        bundle exec rubocop --format json -o report.json

    - name: Run Tests (rspec)
      run: |
        bundle exec rspec
